# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_7Z "")
SET(CPACK_BINARY_BUNDLE "OFF")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "OFF")
SET(CPACK_BINARY_DRAGNDROP "OFF")
SET(CPACK_BINARY_IFW "OFF")
SET(CPACK_BINARY_NSIS "OFF")
SET(CPACK_BINARY_OSXX11 "OFF")
SET(CPACK_BINARY_PACKAGEMAKER "OFF")
SET(CPACK_BINARY_PRODUCTBUILD "OFF")
SET(CPACK_BINARY_RPM "OFF")
SET(CPACK_BINARY_STGZ "ON")
SET(CPACK_BINARY_TBZ2 "OFF")
SET(CPACK_BINARY_TGZ "ON")
SET(CPACK_BINARY_TXZ "OFF")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_BUILD_SOURCE_DIRS "/Users/macbook/workspace/homework/hw02(ex);/Users/macbook/workspace/homework/hw02(ex)/_build")
SET(CPACK_CMAKE_GENERATOR "Unix Makefiles")
SET(CPACK_COMPONENTS_ALL "")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://gitlab.com/Aksiniya/hw02-explorer-2k3s")
SET(CPACK_DEBIAN_PACKAGE_NAME "libexpl-dev")
SET(CPACK_DEBIAN_PACKAGE_PREDEPENDS "cmake >= 3.0")
SET(CPACK_DEBIAN_PACKAGE_RELEASE "1")
SET(CPACK_GENERATOR "STGZ;TGZ")
SET(CPACK_INSTALL_CMAKE_PROJECTS "/Users/macbook/workspace/homework/hw02(ex)/_build;explorer;ALL;/")
SET(CPACK_INSTALL_PREFIX "/Users/macbook/workspace/homework/hw02(ex)/_install")
SET(CPACK_MODULE_PATH "")
SET(CPACK_NSIS_DISPLAY_NAME "explorer 0.1.0.0")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_PACKAGE_NAME "explorer 0.1.0.0")
SET(CPACK_OSX_SYSROOT "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk")
SET(CPACK_OUTPUT_CONFIG_FILE "/Users/macbook/workspace/homework/hw02(ex)/_build/CPackConfig.cmake")
SET(CPACK_PACKAGE_CONTACT "a_strelina@inbox.ru")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "/Users/macbook/workspace/homework/hw02(ex)/DESCRIPTION")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "static c++ library for showing file info")
SET(CPACK_PACKAGE_FILE_NAME "explorer-0.1.0.0-Darwin")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "explorer 0.1.0.0")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "explorer 0.1.0.0")
SET(CPACK_PACKAGE_NAME "explorer")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "Humanity")
SET(CPACK_PACKAGE_VERSION "0.1.0.0")
SET(CPACK_PACKAGE_VERSION_MAJOR "0")
SET(CPACK_PACKAGE_VERSION_MINOR "1")
SET(CPACK_PACKAGE_VERSION_PATCH "0")
SET(CPACK_PACKAGE_VERSION_TWEAK "0")
SET(CPACK_RESOURCE_FILE_LICENSE "/Users/macbook/workspace/homework/hw02(ex)/LICENSE")
SET(CPACK_RESOURCE_FILE_README "/Users/macbook/workspace/homework/hw02(ex)/README.md")
SET(CPACK_RESOURCE_FILE_WELCOME "/usr/local/Cellar/cmake/3.9.3_1/share/cmake/Templates/CPack.GenericWelcome.txt")
SET(CPACK_RPM_CHANGELOG_FILE "/Users/macbook/workspace/homework/hw02(ex)/ChangeLog.md")
SET(CPACK_RPM_PACKAGE_GROUP "explorer")
SET(CPACK_RPM_PACKAGE_LICENSE "MIT")
SET(CPACK_RPM_PACKAGE_NAME "explorer-devel")
SET(CPACK_RPM_PACKAGE_RELEASE "1")
SET(CPACK_RPM_PACKAGE_URL "https://gitlab.com/Aksiniya/hw02-explorer-2k3s")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_7Z "")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/Users/macbook/workspace/homework/hw02(ex)/_build/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_RPM "OFF")
SET(CPACK_SOURCE_TBZ2 "ON")
SET(CPACK_SOURCE_TGZ "ON")
SET(CPACK_SOURCE_TXZ "ON")
SET(CPACK_SOURCE_TZ "ON")
SET(CPACK_SOURCE_ZIP "OFF")
SET(CPACK_SYSTEM_NAME "Darwin")
SET(CPACK_TOPLEVEL_TAG "Darwin")
SET(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/Users/macbook/workspace/homework/hw02(ex)/_build/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
